/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'am' at '12/11/16 09:34' with Gradle 3.0
 *
 * @author am, @date 12/11/16 09:34
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
